### ISSUE TITLE
关于seo

### ISSUE THREAD

**Issue by xingmolu** [yexiaochai/blade#2]
你在博客里说解决来SEO的问题，我想请问下，ajax的网页如何解决SEO的问题呢？谢谢

**Comment by yexiaochai** [comment]
http://www.cnblogs.com/yexiaochai/p/4463420.html
这是第一个方案，第二个方案是做pc倒流的做法，第三是做百度卡片，这个要百度团队才能搞

**Comment by miketwais** [comment]
ajax的网页就不可避免的牺牲了一些seo方面的优势。这个没法避免。

在 2015-10-27 10:53:44，"xingmolu" notifications@github.com 写道：

你在博客里说解决来SEO的问题，我想请问下，ajax的网页如何解决SEO的问题呢？谢谢

**Comment by xingmolu** [comment]
嗯，目前在考虑在php和浏览器之间加个nodejs 层，来做路由和模板渲染，类似于淘宝的方案，但是怕入坑，小团队，怕后面遇到一堆问题不好解决。

**Comment by xingmolu** [comment]
@yexiaochai 第二个方案是做pc倒流的做法  这个方案有例子吗？

**Comment by yexiaochai** [comment]
PC倒流就是PC站点将移动站点需要SEO的页面做成响应式，然后引流到移动站点去

**Comment by xingmolu** [comment]
我们现在pc端的也全是ajax开发的，seo很是纠结了
